### ISSUE TITLE
Metrics are not loaded when running a rails application without rails server

### ISSUE THREAD

**Issue by karsthammer** [yabeda-rb/yabeda-rails#1]
The rails metrics are not automatically added when you, instead of using `rails server`, call the webserver directly (e.g. `puma -C config/puma.rb`).

Calling the webserver directly is a fairly common practice in production, the puma documentation even promotes it when you need to specify puma-specific configuration flags.

I wonder if there is a better way to check if we're running in a rails server then calling `const_defined?(:Server)`.

Is removing the check, and thus always defining the metrics, an option? In that case there are a couple of unused metrics in the /metrics endpoint, but I don't know if that is acceptable.

**Comment by Envek** [comment]
Fix by @daffydowden (thanks!) released as 0.1.2
