### ISSUE TITLE
Not working with Rails API mode

### ISSUE THREAD

**Issue by vk26** [yabeda-rb/yabeda-rails#11]
Hi! I have rails app with only API mode. I tried setup yabeda-prometheus, yabeda-rails, but It's not worked.
`::1 - - [22/May/2020:20:36:01 +08] "GET /metrics HTTP/1.1" 404 17945`
I think, Prometheus expects text exposition format, and send request to app as Content-Type: text/html. But my app hasn't route GET /metrics with html-response.
How can I resolve this problem for Rails api app?

**Comment by Envek** [comment]
Hi! Have you mounted `yabeda-prometheus` exporter to `/metrics` path? [See its README](https://github.com/yabeda-rb/yabeda-prometheus/#usage).

Whether it is API mode or not shouldn't make any difference here.

---

For both Rails and non-Rails applications place following line in your `config.ru` _before_ running your application:

```ruby
use Yabeda::Prometheus::Exporter, path: "/metrics"
```

In Ruby on Rails applications you can add following line in `config/routes.rb` instead:

```ruby
mount Yabeda::Prometheus::Exporter => "/metrics"
```

In both cases your application metrics will be available at `/metrics` endpoint.

**Comment by vk26** [comment]
Really, I missed it. After adding `use Yabeda::Prometheus::Exporter` it's working. Thank you!
