### ISSUE TITLE
Is there a way to serve the rails metrics in same endpoint as yabeda-sidekiq?

### ISSUE THREAD

**Issue by acmh** [yabeda-rb/yabeda-rails#12]
Hi, first thanks for your time and work!

From my understanding, the rails metrics are exposed to the same URL as the application host, e.g if the rails app is at localhost:3000, the metrics are available at localhost:3000/metrics.

It is possible to merge the rails metrics to the same endpoint of yabeda-sidekiq (when using the `start_metrics_server!` method)?
Or for example, serve the rails metrics in another port? (e.g localhost:5000/metrics)

Thanks!

**Comment by Envek** [comment]
If you run web and sidekiq processes on the same machine then you can use [prometheus-client-mmap](https://gitlab.com/gitlab-org/prometheus-client-mmap/) that uses shared memory for metrics storage. In that case rails app and sidekiq will see each others metrics.

If you use Puma, then you can use special `yabeda_prometheus` plugin in [yabeda-puma-plugin](https://github.com/yabeda-rb/yabeda-puma-plugin) (see [Exposing metrics for Prometheus on different port](https://github.com/yabeda-rb/yabeda-puma-plugin#on-different-port))

And yes, you can use `Yabeda::Prometheus::Exporter.start_metrics_server!` to expose metrics on different port in all other cases. See [yabeda-prometheus README](https://github.com/yabeda-rb/yabeda-prometheus#usage) for details.

**Comment by acmh** [comment]
Thanks @Envek for the quick response! I will try those approaches!
