### ISSUE TITLE
Custom on_controller_action: Event missing headers?

### ISSUE THREAD

**Issue by sjdweb** [yabeda-rb/yabeda-rails#21]
Hi,

I've added this custom metric via the hooks:
```ruby
Yabeda::Rails.on_controller_action do |event, labels|
  next unless event.payload[:headers] && event.payload[:headers]["X-Request-Start"]

  now = DateTime.now
  request_start = DateTime.strptime(event.payload[:headers]["X-Request-Start"].gsub("t=", ""), "%Q")

  queue_time_in_seconds = (now.to_time.to_f - request_start.to_time.to_f)

  request_queue_time.measure(labels, queue_time_in_seconds)
end
```

However it seems the headers are missing from the event. According to the [Rails docs](https://guides.rubyonrails.org/v5.0/active_support_instrumentation.html#process-action-action-controller) they should be present. Are they filtered out by this gem?

**Comment by Envek** [comment]
Hmm, weird. No, there is no any filtering.

We just subscribe to the same event here: https://github.com/yabeda-rb/yabeda-rails/blob/74e649e4a0a7fa43f96c9fa5a69b2f85a014f08f/lib/yabeda/rails.rb#L46-L47
And then call hooks here: https://github.com/yabeda-rb/yabeda-rails/blob/74e649e4a0a7fa43f96c9fa5a69b2f85a014f08f/lib/yabeda/rails.rb#L62-L64

Headers should be there.

**Comment by sjdweb** [comment]
@Envek I found some custom hook code around `process_action` in our codebase that is manually overriding the `"process_action.action_controller` event! All good. Thanks for checking.
