### ISSUE TITLE
Is there any way to use this gem with Grape API?

### ISSUE THREAD

**Issue by Prorok64b** [yabeda-rb/yabeda-rails#6]

**Comment by Envek** [comment]
As far as I can see from [Grape](https://github.com/ruby-grape/grape) README it works as Rack application that is mounted to your routes. So there is no rails controllers and actions.

So it looks like **no**, this gem will not work with Grape API. You need to write separate one that will declare grape-specific metrics (I'm not even know how they should be named: actions, endpoints, methods?). I've never worked with Grape so can't really help there.

**Comment by Prorok64b** [comment]
Thanks for reply. I found out the same thing and created gem based on yabeda: https://github.com/efigence/yabeda-grape

I hope, somebody will find out it useful.
