### ISSUE TITLE
Could anyone share some Grafana dashboard

### ISSUE THREAD

**Issue by donaldding** [yabeda-rb/yabeda-rails#7]
It's a very nice gem,  it would be better if with a basic grafana dashboard config 😸

**Comment by Envek** [comment]
Hi! This is definitely nice idea! I think I will be able to beautify my dashboards and publish few dashboards for everyone, but can't say exactly when. Stay tuned!

**Comment by Envek** [comment]
Sorry for the late reply. Here is the links to sample Grafana dashboards:

 - for `yabeda-rails`: https://grafana.com/grafana/dashboards/11668
 - for `yabeda-sidekiq`: https://grafana.com/grafana/dashboards/11667

These should be considered as template and starting point for building your own dashboards.

**Comment by donaldding** [comment]
It's very helpful ! Thanks @Envek

**Comment by iwikus** [comment]
Any hints how to add multiple nodes to yabeda-rails https://grafana.com/grafana/dashboards/11668 ?

**Comment by Envek** [comment]
What do you mean under multiple nodes? Metrics for every instance?
You can filter by [`instance` label](https://prometheus.io/docs/concepts/jobs_instances/) (it can be relabeled to something like `hostname` on Prometheus level though).
And also you can [repeat panels for variable values in Grafana](https://grafana.com/blog/2020/06/09/learn-grafana-how-to-automatically-repeat-rows-and-panels-in-dynamic-dashboards/).
Hope this helps.

**Comment by iwikus** [comment]
Yes, like "node_exporter full" dashboards have ![image](https://github.com/yabeda-rb/yabeda-rails/assets/30178330/e909ec1a-ac53-4882-8664-ac6bd162dc3b).

**Comment by iwikus** [comment]
Thanks Envek, your hint helped me to solve it (using redis dashboard also as example).
I have defined new variable 
![image](https://github.com/yabeda-rb/yabeda-rails/assets/30178330/29d26fff-3410-4201-803d-52a8e3e8f4c8)

and then added into dashboard json definition {instance=~\"$instance\"} everywhere to expr.

`"expr": "sum(rate(rails_requests_total{instance=~\"$instance\"}[1m])) by (status)",`
